---
- name: Update packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install software
  apt: name={{item}} state=present
  with_items:
    - nginx
    - python-pip
    - pip
- name: Install pip latest
  pip:
    name: pip
    state: latest
    extra_args: --user
  become: false